[window]
dynamic_padding = false
decorations = "none"
opacity = 0.3

padding.x = 0
padding.y = 0

decorations_theme_variant = "Dark"

[font]
size = 13

normal.family = "JetBrainsMonoNerdFont"
normal.style = "Light"

bold.family = "JetBrainsMonoNerdFont"
bold.style = "Medium"

italic.family = "JetBrainsMonoNerdFont"
italic.style = "Light Italic"

offset.x = 0
offset.y = 0

glyph_offset.x = 0
glyph_offset.y = 0


[colors.primary]
# hard contrast background = = '#1d2021'
background = '#000000'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'


[cursor]
# style = "Beam"
